export let videoTypes = [
    "VHS",
    "S-VHS",
    "VHSc",
    "miniDV",
    "DVD",
    "Mini DVD",
    "Betamax",
    "Betacam SP",
    "U-matic",
    "DVCAM",
    "HD miniDV",
    "PAL VHS",
    "PAL S-VHS",
    "PAL VHSc",
    "PAL miniDV",
    "PAL DVD",
    "PAL Mini DVD",
    "PAL Betamax",
    "PAL Betacam SP",
    "PAL U-matic",
    "PAL DVCAM",
    "PAL HD miniDV",
]